# -*- encoding: utf-8 -*-
require_relative 'lib/px4_log_reader'

Gem::Specification.new do |s|
   s.name        = 'px4_log_reader'
   s.version     = Px4LogReader::VERSION
   s.date        = Time.now.to_date.strftime('%Y-%m-%d')
   s.summary     = "PX4 flight log reader"
   s.description = "Px4LogReader is a gem for parsing PX4-format flight logs generated by the Pixhawk."
   s.authors     = [ "Robert Glissmann" ]
   s.email       = 'Robert.Glissmann@gmail.com'
   s.files       = `git ls-files`.split("\n")
   s.licenses    = ['BSD']
   s.homepage    = 'https://github.com/rgmann/px4_log_reader'

   s.add_development_dependency 'rspec', '~> 3.1'
end